package fr.umlv.corba.calculator.proxy;


/**
* fr/umlv/corba/calculator/proxy/_CorbaCalculatorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/calculator.idl
* samedi 25 février 2006 19 h 16 CET
*/

public class _CorbaCalculatorStub extends org.omg.CORBA.portable.ObjectImpl implements fr.umlv.corba.calculator.proxy.CorbaCalculator
{

  public void push (short value) throws fr.umlv.corba.calculator.proxy.ArithmeticException, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("push", true);
                $out.write_short (value);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/ArithmeticException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.ArithmeticExceptionHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                push (value        );
            } finally {
                _releaseReply ($in);
            }
  } // push

  public short pop () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pop", true);
                $in = _invoke ($out);
                short $result = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pop (        );
            } finally {
                _releaseReply ($in);
            }
  } // pop

  public short top () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("top", true);
                $in = _invoke ($out);
                short $result = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return top (        );
            } finally {
                _releaseReply ($in);
            }
  } // top

  public void add () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("add", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                add (        );
            } finally {
                _releaseReply ($in);
            }
  } // add

  public void sub () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sub", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sub (        );
            } finally {
                _releaseReply ($in);
            }
  } // sub

  public void mult () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mult", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                mult (        );
            } finally {
                _releaseReply ($in);
            }
  } // mult

  public void div () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.ArithmeticException, fr.umlv.corba.calculator.proxy.UnKnowErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("div", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:proxy/InvalidNumberOfOperators:1.0"))
                    throw fr.umlv.corba.calculator.proxy.InvalidNumberOfOperatorsHelper.read ($in);
                else if (_id.equals ("IDL:proxy/ArithmeticException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.ArithmeticExceptionHelper.read ($in);
                else if (_id.equals ("IDL:proxy/UnKnowErrorException:1.0"))
                    throw fr.umlv.corba.calculator.proxy.UnKnowErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                div (        );
            } finally {
                _releaseReply ($in);
            }
  } // div

  public void reset ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reset", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                reset (        );
            } finally {
                _releaseReply ($in);
            }
  } // reset

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:proxy/CorbaCalculator:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _CorbaCalculatorStub
