package fr.umlv.corba.calculator.proxy;


/**
* fr/umlv/corba/calculator/proxy/CorbaCalculatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/calculator.idl
* mardi 21 février 2006 20 h 14 CET
*/

abstract public class CorbaCalculatorHelper
{
  private static String  _id = "IDL:proxy/CorbaCalculator:1.0";

  public static void insert (org.omg.CORBA.Any a, fr.umlv.corba.calculator.proxy.CorbaCalculator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static fr.umlv.corba.calculator.proxy.CorbaCalculator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (fr.umlv.corba.calculator.proxy.CorbaCalculatorHelper.id (), "CorbaCalculator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static fr.umlv.corba.calculator.proxy.CorbaCalculator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaCalculatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, fr.umlv.corba.calculator.proxy.CorbaCalculator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static fr.umlv.corba.calculator.proxy.CorbaCalculator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof fr.umlv.corba.calculator.proxy.CorbaCalculator)
      return (fr.umlv.corba.calculator.proxy.CorbaCalculator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      fr.umlv.corba.calculator.proxy._CorbaCalculatorStub stub = new fr.umlv.corba.calculator.proxy._CorbaCalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static fr.umlv.corba.calculator.proxy.CorbaCalculator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof fr.umlv.corba.calculator.proxy.CorbaCalculator)
      return (fr.umlv.corba.calculator.proxy.CorbaCalculator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      fr.umlv.corba.calculator.proxy._CorbaCalculatorStub stub = new fr.umlv.corba.calculator.proxy._CorbaCalculatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
