package fr.umlv.corba.calculator.proxy;


/**
* fr/umlv/corba/calculator/proxy/CorbaCalculatorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/calculator.idl
* mercredi 1 février 2006 15 h 25 CET
*/

public abstract class CorbaCalculatorPOA extends org.omg.PortableServer.Servant
 implements fr.umlv.corba.calculator.proxy.CorbaCalculatorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("push", new java.lang.Integer (0));
    _methods.put ("pop", new java.lang.Integer (1));
    _methods.put ("add", new java.lang.Integer (2));
    _methods.put ("minus", new java.lang.Integer (3));
    _methods.put ("mult", new java.lang.Integer (4));
    _methods.put ("div", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // proxy/CorbaCalculator/push
       {
         short value = in.read_short ();
         this.push (value);
         out = $rh.createReply();
         break;
       }

       case 1:  // proxy/CorbaCalculator/pop
       {
         short $result = (short)0;
         $result = this.pop ();
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 2:  // proxy/CorbaCalculator/add
       {
         this.add ();
         out = $rh.createReply();
         break;
       }

       case 3:  // proxy/CorbaCalculator/minus
       {
         this.sub ();
         out = $rh.createReply();
         break;
       }

       case 4:  // proxy/CorbaCalculator/mult
       {
         this.mult ();
         out = $rh.createReply();
         break;
       }

       case 5:  // proxy/CorbaCalculator/div
       {
         this.div ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:proxy/CorbaCalculator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaCalculator _this() 
  {
    return CorbaCalculatorHelper.narrow(
    super._this_object());
  }

  public CorbaCalculator _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaCalculatorHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaCalculatorPOA
