package fr.umlv.corba.calculator.proxy;


/**
* fr/umlv/corba/calculator/proxy/CorbaCalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/calculator.idl
* samedi 25 février 2006 17 h 03 CET
*/

public interface CorbaCalculatorOperations 
{
  void push (short value) throws fr.umlv.corba.calculator.proxy.ArithmeticException, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  short pop () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  short top () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  void add () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  void sub () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  void mult () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  void div () throws fr.umlv.corba.calculator.proxy.InvalidNumberOfOperators, fr.umlv.corba.calculator.proxy.ArithmeticException, fr.umlv.corba.calculator.proxy.UnKnowErrorException;
  void reset ();
} // interface CorbaCalculatorOperations
