package fr.umlv.corba.calculator.proxy;


/**
* fr/umlv/corba/calculator/proxy/CorbaCalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/calculator.idl
* mercredi 1 février 2006 15 h 25 CET
*/

public interface CorbaCalculatorOperations 
{
  void push (short value);
  short pop ();
  void add ();
  void sub ();
  void mult ();
  void div ();
} // interface CorbaCalculatorOperations
